# Generated by Django 5.0.2 on 2024-09-17 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_alter_emprestimos_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 19, 43, 27, 762481)),
        ),
    ]
