# Generated by Django 5.0.2 on 2024-09-18 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='livro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livro.livros'),
        ),
    ]
